### ISSUE TITLE
Drop requirement for patch_ep_host_etcd

### ISSUE THREAD

**Issue by russellb** [metalkube/kni-installer#69] opened 2019-04-30 17:55 UTC
dev-scripts currently runs the following:

`patch_ep_host_etcd $CLUSTER_DOMAIN`

The related code is:

```
function patch_ep_host_etcd() {
    local host_etcd_ep
    local hostnames
    local address

    declare -a etcd_hosts
    declare -r domain="$1"
    declare -r srv_record="_etcd-server-ssl._tcp.$domain"
    declare -r api_domain="api.$domain"
    host_etcd_ep=$(oc get ep -n kube-system host-etcd -o json | jq -r '{"subsets": .subsets}')
    echo -n "Looking for etcd records"
    while ! host -t SRV "$srv_record" "$api_domain" >/dev/null 2>&1; do
        echo -n "."
        sleep 1
    done
    echo " Found!"

    mapfile -t hostnames < <(dig +noall +answer -t SRV "$srv_record" "@$api_domain" | awk '{print substr($NF, 1, length($NF)-1)}')

    for hostname in "${hostnames[@]}"; do
        address=$(dig +noall +answer "$hostname" "@$api_domain" | awk '$4 == "A" {print $NF}')
        etcd_hosts+=($address\ $hostname)
    done
    patch=$(python -c "$(cat << 'EOF'
import json
import sys
import yaml

patch = json.loads(sys.argv[1])
addresses = []
for entry in sys.argv[2:]:
    ip, hostname = entry.split()

    if '.' in hostname:
        hostname = hostname.split('.')[0]
    addresses.append({'ip': ip, 'hostname': hostname})

# remove old address entries
del patch['subsets'][0]['addresses']
patch['subsets'][0]['addresses'] = addresses
print(yaml.safe_dump(patch))
EOF
    )" "$host_etcd_ep" "${etcd_hosts[@]}")
    oc -n kube-system patch ep/host-etcd --patch "$patch"
}
```

The installer needs to be updated to do whatever is needed to avoid this hack.

**Comment by russellb** [comment] 2019-04-30 17:55
@celebdor can you add more info about this?

**Comment by stbenjam** [comment] 2019-06-13 20:42
I think https://github.com/openshift-metal3/dev-scripts/issues/333 is a dupe of this. I've also proposed removal here - https://github.com/openshift-metal3/dev-scripts/pull/620.

**Comment by stbenjam** [comment] 2019-06-14 10:48
Removed in https://github.com/openshift-metal3/dev-scripts/pull/620

**Closed as completed by stbenjam** 2019-06-14 10:48 UTC
